name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform:iOS Simulator, OS:16.0, name:iPad (9th generation)']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Choosing Xcode
        run: sudo xcode-select -switch /Application/Xcode_14.0.1.app
      - name: Build
        run: |
          xcodebuild clean build -project "Dictionary.xcodeproj" -scheme "Dictionary" -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          xcodebuild clean test -project "Dictionary.xcodeproj" -scheme "DictionaryTests" -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
  
